apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"   # dependency layer: after postgres, before trino
spec:
  project: default
  source:
    repoURL: https://github.com/huynguyn2000/my-data-platform-gitops
    targetRevision: main
    path: apps/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
